### ISSUE TITLE
Refactor visualization script

### ISSUE THREAD

**Issue by sheridana** [talmolab/biogtr#17]
# Suggestions for the visualization [script](https://github.com/talmolab/biogtr/blob/main/biogtr/visualize.py)

---

### Efficiency

It is not efficient at the moment and won't work for large videos. This line:

```py
video = np.stack([vid_reader.get_data(i) for i in sorted(labels["Frame"].unique())])
```

Will load all of the frame data in memory from the video reader. Quick fix is to just pass the `vid_reader` directly into the `annotate_video` function. Then this loop:

```py
for i in sorted(labels["Frame"]):
     frame = video[i]
```

could just be:

```py
for i in sorted(labels["Frame"].unique()):
     frame = video.get_data(i)
```

Also, this assumes that the input video is an mp4 file. This script should also work for tif files, with lazy loading. The [LazyTiffStack](https://github.com/talmolab/biogtr/blob/e30a6b59e32e88716be3cba02662028976fb2fde/biogtr/datasets/data_utils.py#L349) could be used for this, e.g something like:

```py
from biogtr.datasets.data_utils import LazyTiffStack

if cfg.vid_path.endswith('.mp4'):
     vid_reader = imageio.get_reader(cfg.vid_path, "ffmpeg")
else:
     vid_reader = LazyTiffStack(cfg.vid_path)
```

Then you would need also logic in the `annotate_video` function to either `get_section` or `get_data` based on the vid_reader type. But a better solution is to just change the `get_section` function in `LazyTiffStack` to `get_data`. 

---

### RGB vs Grayscale

These conversions:

```py
if frame.shape[0] == 1 or frame.shape[-1] == 1:
     frame = cv2.cvtColor((frame * 255).astype(np.uint8), cv2.COLOR_GRAY2RGB)
else:
     frame = (frame * 255).astype(np.uint8).copy()
```

Don't handle cases where the data is already uint8 between 0 & 255. Should just add a check before scaling.

---

### Saving args

When saving the video, we pass some args:

```py
imageio.mimwrite(f"{ds_name}.mp4", data, fps=fps, macro_block_size=1)
```

It could also be good to optionally scale the image size (e.g if saving really large videos). And then can better control these with a kwargs dict:

```py
w = 512
h = 512
macro_block_size = 1

kwargs = {
     'fps': fps,
     'macro_block_size': macro_block_size,
     'ffmpeg_params': ['-s',f'{w}x{h}']
}

for idx, (ds_name, data) in enumerate([(vid_path, annotated_frames)]):
     imageio.mimwrite(f"{ds_name}.mp4", data, **kwargs)
```

But pass them as func args

**Comment by aaprasad** [comment]
This has been fixed
