### ISSUE TITLE
Landmark-anchored crops and position embeddings

### ISSUE THREAD

**Issue by talmo** [talmolab/biogtr#32]
Pose makes it hard to be insensitive to visibility of the anchor landmark since it's often the case that an anchor node is missing, or too close to other instances to make the crops distinguishable.

Example:
![image](https://github.com/talmolab/biogtr/assets/3187454/729c0474-a53c-4197-bfac-2b0bf9a7a0c7)

One way to make this less sensitive to center-cropping is to crop around each visible landmark and stack them channelwise into a `(crop_size, crop_size, nodes * channels)` array that gets fed into the visual encoder.

Here's an example vectorized cropping function with missing landmark handling:

```py
def get_patches(frame_idx, patch_size=5):

    xv = np.arange(-patch_size // 2 + 1, patch_size // 2 + 1)
    yv = np.arange(-patch_size // 2 + 1, patch_size // 2 + 1)
    grid = np.stack(np.meshgrid(xv, yv), axis=-1)

    poses = trx[frame_idx]
    centers = np.round(poses)
    centers = np.where(np.isnan(centers), 0, centers)

    img = read_frame(frame_idx)

    patch_inds = centers.reshape(centers.shape[0], centers.shape[1], 1, 1, 2) + grid
    patch_inds[..., 1] = np.clip(patch_inds[..., 1], 0, img.shape[0] - 1)
    patch_inds[..., 0] = np.clip(patch_inds[..., 0], 0, img.shape[1] - 1)
    patch_inds = patch_inds.astype(int)

    patches = img[patch_inds[..., 1], patch_inds[..., 0]]

    mask = np.isnan(poses).any(axis=-1)

    patches = np.where(mask.reshape(poses.shape[0], poses.shape[1], 1, 1, 1), 0, patches)

    return patches, mask
```

----

The next issue is how to deal with the position embedding.

Options:

1. Use the bbox that covers all visible nodes. This will change the position embedding drastically from frame-to-frame as nodes pop in and out of visibility, but it's the simplest approach.
2. Embed each node's crop bbox individually into `(nodes, embedding_dim)` and then reduce to `(embedding_dim,)`. But how do we reduce? A simple averaging makes this basically equivalent to using the midpoint. Maybe concatenate to `(nodes * embedding_dim,)` and project down via a small MLP?

**Comment by aaprasad** [comment]
done in #41
